version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: weekly
    day: saturday
- package-ecosystem: devcontainers
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
