---
- name: Install Docker CLI tools (Homebrew)
  become: true
  become_user: '{{ my_user }}'
  community.general.homebrew:
    name:
      - ctop
      - dive
    state: present
  environment:
    HOMEBREW_INSTALL_FROM_API: '1'
