---
# Configure Xfce desktop
- name: create xfce4 config directory
  file:
    path: /home/vagrant/.config/xfce4/xfconf/xfce-perchannel-xml
    state: directory
    owner: vagrant
    group: vagrant
- name: write xfce4 power manager config
  template:
    src: xfce4-power-manager.xml
    dest: /home/vagrant/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
    owner: vagrant
    group: vagrant
- name: write xfce4 panel config
  template:
    src: xfce4-panel.xml
    dest: /home/vagrant/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
    owner: vagrant
    group: vagrant

# Install Xfce desktop
- name: install xubuntu-core
  apt:
    name: xubuntu-core
    state: present
- name: install xfce4-mixer
  apt:
    name: xfce4-mixer
    state: present

# Remove screensaver (host OS has screensaver)
- name: uninstall xscreensaver
  apt:
    name: xscreensaver
    state: absent

# Install text editor
- name: install gedit
  apt:
    name: gedit
    state: present

# Install Seahorse SSH agent GUI
- name: install seahorse
  apt:
    name: seahorse-daemon
    state: present

# Install and configure DockbarX docbar for Xfce
- name: create xfce4 dockbarx config directory
  file:
    path: /home/vagrant/.config/xfce4/panel
    state: directory
    owner: vagrant
    group: vagrant
- name: write xfce4 dockbarx config
  template:
    src: dockbarx-9.rc
    dest: /home/vagrant/.config/xfce4/panel/dockbarx-9.rc
    owner: vagrant
    group: vagrant
- name: add dockbarx ppa
  apt_repository:
    repo: 'ppa:dockbar-main/ppa'
- name: install dockbarx
  apt:
    name: dockbarx
    state: present
- name: install xfce4-dockbarx-plugin
  apt:
    name: xfce4-dockbarx-plugin
    state: present
