---
# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

rvm:
  # Specify Ruby version
  - '2.2'

python:
  # Specify Python version
  - '2.7'

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install lint tools.
  - gem install rubocop

  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Run build script
  - .travis/build.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

env:
  global:
    # GIT_USERNAME
    - secure: ZnCqgsXRyxVoA8YPNgqRxbzpCitQYehAyvnDj8hEJ/KK6O4WBAgNnnNnMaLGbFopgrcEDLyo4e+3Kju+BL3aXczPDbBK9sfktmxWSvGFynu/XouuB0ecFlnBxANS+LaYDf5fypK9S6aOECy5Kev/+VosZwe/RyKK8H+1T9a20Ee8hOtyu4KrSfg2YdF0fw9Wgdo4FslWw0lEhEHeS27CltMRkAhg86CbxIkhdvYpQmbJw5wPwY5GzwEAWlpbngEqvdaCKw5Dt2pKG7RYnCw5F0vNfswnvEOa5nHWkpOASJtMA9isVM0kr1jVr2uXd5UhgjffL99gWwS9QVsqZCcSclFgktl9l+0bDhDKXiHrnapMJVKMT/dBGeAvva4Wkq9J9Q6n6B5U+3NDSibS5S03ri7cHvbj88waHiXHsjSCXCZvrFxp4fSx9Wh29F9ueX8fpZhgGqZ5j43Rz4WAhqigA1Z5U3C/u8AGCe0Pi/1JQkuGxBb3pzCPljk9toryF/FJYuH/n/yzHWoYPcWcsYan4SRdqJS+hVcKYapluRf6so2ZZQ01o4k8AqHJsTGqDHPEjGCAqvnWENHGZ5TbyogjAJqP7WxI6QHH1EZv9cw1CCnWQoQE2Q6qzU/NrltfcEOWlpoX+/Dsd2FNAB4pLqqhBWtbgJP0HwiB++WO6O3iBaU=
    # GIT_PASSWORD
    - secure: Poth56B8Mnyl5m5tz5XXaJ/Yxy6oQX6tKUBcnIaFT9M/EDLsdrTVq5i5XXWfOSkFF7o/9IED5NVrvoZsHLuSYvCkdNZxjddydRT2LLvJRAbnFJ61N0fJbGpnef0UQekY9VPHoRPYPDJXExg+V6SzCPa2+DpRB9WtDtEQ1tfKrccPa29vNsds2VWALCAo5TYy8UCR2oyyLgJlylOU1wJBcruYIOg3SqfFyK3p8q5g84TmNzGD8uNz4wGXsOJoLdi6m2N4EVd8uCyy2TljvCp5hTG4jU9uhRgEChTNsK8MJvRKRU3gJ4ggIHIahYKGgW0+55/lUv1JkM5SokiqlgxfCQ/ufPCpkYA3X7di0Rf3ZVgYMQDeUl1wctRbfk1nkvi8Rr2FIYNJ7gssCX7KnSb6NysumJWu9LYwoGGoe0H2JO9omUMY1DVWf3T9ceHGBLVgG67H72W6zQRuCA9Xb6AIDbfns993kBBNnJRluDYx2glneIBmyFmNZUei8Qz3Sg7aOAnmWcST7cdMN81FqaJBurLZRMf24Pg/3AF9WUNexw6GXf+vzFsPLUwl4JO9JZjBK9AbKdG9gF17NnyH98GSiHUxRa87+fe0hJTfq7DQcONHtEwjl1pr7AqUIGL5ICknrDx6kjP9Fcq9TANFh+1krN1P4jwycwTsrL4clhLKeTA=
