---
# Require the standard build environment
sudo: required

rvm:
  # Specify Ruby version
  - '2.2'

python:
  # Specify Python version
  - '2.7'

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install lint tools.
  - gem install rubocop

  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Run build script
  - .travis/build.sh
