---
- name: Install Kubernetes CLI tools (Homebrew)
  become: true
  become_user: '{{ my_user }}'
  community.general.homebrew:
    name:
      - kubectx
      - kustomize
      - stern
    state: present
  environment:
    HOMEBREW_INSTALL_FROM_API: '1'
