---
- name: Install Pip
  become: true
  become_user: root
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install Pipenv
  ansible.builtin.pip:
    name: pipenv
    state: present
    extra_args: --user
