---
# filename of IntelliJ IDEA redistributable package
idea_redis_filename: "ideaIU-{{ idea_version }}.tar.gz"

# Name to use in the desktop link
idea_application_name: IntelliJ IDEA

# Dockbar group
idea_startup_wm_class: jetbrains-idea

# Name of desktop file
idea_desktop_filename: jetbrains-idea.desktop

# Name of the directory where user specific settings are stored
idea_user_dir: .IntelliJIdea{{ idea_version | regex_replace('([0-9]+\.[0-9]+)(\..*)?', '\\1') }}
