---
- hosts: all

  pre_tasks:

    # Install alt-galaxy
    - name: install alt-galaxy
      become: yes
      unarchive:
        src: https://github.com/gantsign/alt-galaxy/releases/download/1.4.1/alt-galaxy_linux_amd64.tar.xz
        remote_src: yes
        dest: /usr/local/bin

    # Install repository keys
    - name: add kubernetes key
      become: yes
      apt_key:
        id: '6A030B21BA07F4FB'
        url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
        state: present

    # Reduce the number of times `apt-get update` needs to be run by
    # pre-registering repositories
    - name: pre-register apt repositories
      become: yes
      apt_repository:
        repo: '{{ item }}'
        update_cache: no
      with_items:
        - ppa:git-core/ppa
        - ppa:webupd8team/atom
        - 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
      register: register_repos

    - name: apt-get update
      become: yes
      apt:
        update_cache: yes
      when: register_repos.changed
