---
- hosts: all

  pre_tasks:

    # Reduce the number of times `apt-get update` needs to be run by
    # pre-registering repositories

    - name: Create APT keyrings dir
      become: yes
      file:
        path: '/etc/apt/keyrings'
        state: directory
        mode: 'u=rwx,go=rx'

    - name: add kubernetes key
      become: yes
      get_url:
        url: 'https://dl.k8s.io/apt/doc/apt-key.gpg'
        dest: '/etc/apt/keyrings/kubernetes-archive-keyring.gpg'
        mode: 'u=rw,go=r'
        force: yes
      tags:
        - docker
        - kubernetes

    - name: add kubernetes repo
      become: yes
      apt_repository:
        repo: >-
          deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg]
          http://apt.kubernetes.io/ kubernetes-xenial main
        update_cache: no
      tags:
        - docker
        - kubernetes
      register: kubernetes_repo

    - name: add Google Linux key
      become: yes
      get_url:
        url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
        dest: '/etc/apt/keyrings/linux.google.asc'
        mode: 'u=rw,go=r'
        force: yes
      tags:
        - gui
        - chrome

    - name: add Google Chrome repo
      become: yes
      apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/linux.google.asc]
          https://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        update_cache: no
      tags:
        - gui
        - chrome
      register: chrome_repo

    - name: add vscode key
      become: yes
      get_url:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        dest: '/etc/apt/keyrings/'
        mode: 'u=rw,go=r'
        force: yes
      tags:
        - gui
        - vscode

    - name: add vscode repo
      become: yes
      apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc]
          https://packages.microsoft.com/repos/code stable main
        filename: vscode
        update_cache: no
      tags:
        - gui
        - vscode
      register: vscode_repo

    - name: apt-get update
      become: yes
      apt:
        update_cache: yes
      when: >
        (kubernetes_repo is defined and kubernetes_repo.changed)
        or (chrome_repo is defined and chrome_repo.changed)
        or (vscode_repo is defined and vscode_repo.changed)
