---
- hosts: all
  sudo: true
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
  roles:
    - role: unison
      includeDirectories:
        - .ssh
        - .m2
      includeFiles:
        - .bash_history
        - .zsh_history
        - .gitconfig
      ignorePaths:
        - Path .ssh/authorized_keys
        - BelowPath .m2/repository
    - role: keyboard
      model: pc105
      layout: gb
    - system
    - common-cli
    - role: franklinkim.git
      git_config:
        core:
          autocrlf: input
        alias:
          ls: 'log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate'
          ll: 'log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
          lds: 'log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=short'
          rom: 'rebase origin/master'
    - role: angstwad.docker_ubuntu
      docker_group_members:
        - vagrant
    - role: azavea.java
      java_flavor: openjdk
      java_major_version: '8'
      java_version: '8*'
    - role: groover.maven
      maven_version: 3.3.9
      maven_redis_sha256sum: 6e3e9c949ab4695a204f74038717aa7b2689b1be94875899ac1b3fe42800ff82
      maven_mirror: "http://mirrors.ukfast.co.uk/sites/ftp.apache.org/maven/maven-{{ maven_version|regex_replace('\\..*', '') }}/{{ maven_version }}/binaries"
    - role: franklinkim.environment
      environment_config:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        M2_HOME: "{{ ansible_local.maven.general.maven_home }}"
    - role: franklinkim.users-oh-my-zsh
      users:
        - name: Vagrant
          username: vagrant
          authorized_keys: []
          oh_my_zsh:
            theme: robbyrussell
            plugins: command-not-found docker git mvn
