---
- hosts: all
  sudo: true
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - system
    - role: angstwad.docker_ubuntu
      docker_group_members:
        - vagrant
