---
- hosts: all
  sudo: true
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - role: keyboard
      model: pc105
      layout: gb
    - system
    - common-cli
    - role: angstwad.docker_ubuntu
      docker_group_members:
        - vagrant
