---
- hosts: all
  sudo: true
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - role: unison
      includeDirectories:
        - .ssh
      includeFiles:
        - .bash_history
        - .zsh_history
      ignorePaths:
        - Path .ssh/authorized_keys
    - role: keyboard
      model: pc105
      layout: gb
    - system
    - common-cli
    - role: angstwad.docker_ubuntu
      docker_group_members:
        - vagrant
    - role: franklinkim.users-oh-my-zsh
      users:
        - name: Vagrant
          username: vagrant
          authorized_keys: []
          oh_my_zsh:
            theme: robbyrussell
            plugins: command-not-found docker
