---
- src: franklinkim.timezone
  version: '1.0.0'
- src: angstwad.docker_ubuntu
  version: 'v1.1.8'
- src: franklinkim.git
  version: '1.2.1'
- src: franklinkim.environment
  version: '1.2.0'
- src: cmprescott.chrome
  version: '0.2.2'
- src: geerlingguy.nodejs
  version: '3.2.0'
- src: tersmitten.locales
  version: 'v1.0.3'
- src: gantsign.apt
  version: '1.1.1'
- src: gantsign.atom
  version: '1.1.1'
- src: gantsign.audio
  version: '1.1.1'
- src: https://github.com/gantsign/ansible-role-command-line-tools/archive/1.1.1.tar.gz
  name: gantsign.command-line-tools
- src: gantsign.gitkraken
  version: '2.0.1'
- src: gantsign.intellij
- src: gantsign.java
  version: '3.0.3'
- src: gantsign.keyboard
  version: '1.1.2'
- src: gantsign.lightdm
  version: 'v2.0.0'
- src: gantsign.maven
  version: '3.0.2'
- src: gantsign.maven-color
  version: '3.0.2'
- src: gantsign.maven-notifier
  version: '2.0.2'
- src: gantsign.molecule
  version: '1.0.0'
- src: gantsign.oh-my-zsh
  version: '1.1.0'
- src: gantsign.pin-to-launcher
  version: '1.0.0'
- src: https://github.com/gantsign/ansible-role-unison/archive/1.1.1.tar.gz
  name: gantsign.unison
- src: gantsign.visual-studio-code
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/1.3.0.tar.gz
  name: gantsign.xdesktop
- src: gantsign.zram-config
  version: '1.1.1'
