---
- src: geerlingguy.docker
  version: '4.2.1'
- src: weareinteractive.git
  version: '1.3.3'
- src: weareinteractive.environment
  version: '1.5.0'
- src: geerlingguy.nodejs
  version: '6.0.0'
- src: oefenweb.locales
  version: 'v1.0.48'
- src: gantsign.antigen
  version: '1.4.2'
- src: gantsign.antigen_bundles
  version: '1.3.0'
- src: gantsign.apt
  version: '1.3.1'
- src: gantsign.audio
  version: '2.0.1'
- src: gantsign.backup
  version: '1.0.3'
- src: gantsign.bat
- src: https://github.com/gantsign/ansible-role-command-line-tools/archive/2.2.0.tar.gz
  name: gantsign.command-line-tools
- src: gantsign.ctop
- src: gantsign.default-web-browser
  version: '4.0.0'
- src: gantsign.fd
- src: gantsign.git_credential_manager
- src: gantsign.git_user
  version: '1.2.0'
- src: gantsign.gnome-proxy
  version: '1.2.1'
- src: gantsign.golang
  version: '2.10.1'
- src: gantsign.helm
- src: gantsign.hub
- src: gantsign.inotify
  version: '1.2.2'
- src: gantsign.intellij
- src: gantsign.intellij_jdks
  version: '2.0.1'
- src: gantsign.intellij-plugins
  version: '3.1.1'
- src: gantsign.java
  version: '11.0.0'
- src: gantsign.keyboard
  version: '1.5.0'
- src: gantsign.kompose
- src: gantsign.kubernetes
  version: '3.1.0'
- src: gantsign.lightdm
  version: 'v3.0.1'
- src: gantsign.maven
  version: '5.6.3'
- src: gantsign.maven-notifier
  version: '3.0.2'
- src: gantsign.minikube
- src: gantsign.pin-to-launcher
  version: '4.0.0'
- src: gantsign.pwquality
  version: '1.0.1'
- src: gantsign.pyenv
  version: '2.0.0'
- src: gantsign.sdkman
  version: '2.1.3'
- src: gantsign.sdkman_init
  version: '1.2.2'
- src: gantsign.swapspace
  version: '1.0.1'
- src: gantsign.timezone
  version: '1.1.1'
- src: gantsign.visual-studio-code
  version: '6.8.0'
- src: gantsign.visual-studio-code-extensions
  version: '2.4.0'
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/6.0.0.tar.gz
  name: gantsign.xdesktop
- src: gantsign.zswap
  version: '1.0.1'
