---
- src: franklinkim.timezone
  version: '1.0.0'
- src: angstwad.docker_ubuntu
  version: 'v3.6.2'
- src: franklinkim.git
  version: '1.2.2'
- src: weareinteractive.environment
  version: '1.3.0'
- src: cmprescott.chrome
  version: '0.2.4'
- src: geerlingguy.nodejs
  version: '4.2.2'
- src: oefenweb.locales
  version: 'v1.0.23'
- src: gantsign.antigen
  version: '1.1.0'
- src: gantsign.antigen_bundles
  version: '1.1.0'
- src: gantsign.apt
  version: '1.3.0'
- src: gantsign.atom
  version: '2.0.1'
- src: gantsign.atom-packages
  version: '1.2.0'
- src: gantsign.audio
  version: '1.3.1'
- src: gantsign.backup
  version: '1.0.0'
- src: https://github.com/gantsign/ansible-role-command-line-tools/archive/1.4.0.tar.gz
  name: gantsign.command-line-tools
- src: gantsign.ctop
  version: '1.0.0'
- src: gantsign.default-web-browser
  version: '3.2.0'
- src: gantsign.git_credential_manager
  version: '1.0.0'
- src: gantsign.git_user
  version: '1.0.0'
- src: gantsign.gnome-proxy
  version: '1.2.0'
- src: gantsign.golang
  version: '1.6.0'
- src: gantsign.helm
  version: '1.0.0'
- src: gantsign.hub
  version: '1.0.0'
- src: gantsign.inotify
  version: '1.2.0'
- src: gantsign.intellij
- src: gantsign.intellij-plugins
  version: '1.4.1'
- src: gantsign.java
  version: '5.1.0'
- src: gantsign.keyboard
  version: '1.4.0'
- src: gantsign.kompose
  version: '1.0.0'
- src: gantsign.kubernetes
  version: '2.0.1'
- src: gantsign.lightdm
  version: 'v2.3.0'
- src: gantsign.maven
  version: '5.1.0'
- src: gantsign.maven-notifier
  version: '2.5.0'
- src: gantsign.minikube
  version: '1.0.0'
- src: gantsign.molecule
  version: '4.4.0'
- src: gantsign.postman
  version: '2.3.0'
- src: gantsign.pin-to-launcher
  version: '3.0.1'
- src: gantsign.sdkman
  version: '1.0.0'
- src: gantsign.sdkman_init
  version: '1.0.0'
- src: gantsign.terminator
  version: '2.0.1'
- src: gantsign.visual-studio-code
  version: '5.1.0'
- src: gantsign.visual-studio-code-extensions
  version: '1.5.0'
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/3.0.1.tar.gz
  name: gantsign.xdesktop
- src: gantsign.zram_config
  version: '1.4.1'
