---
- src: franklinkim.timezone
- src: angstwad.docker_ubuntu
- src: franklinkim.users-oh-my-zsh
- src: franklinkim.git
- src: groover.java
- src: franklinkim.environment
- src: groover.util
  name: silpion.util
- src: groover.maven
- src: cmprescott.chrome
- src: gantsign.apt
- src: gantsign.atom
- src: gantsign.audio
- src: https://github.com/gantsign/ansible-role-command-line-tools
  name: gantsign.command-line-tools
- src: gantsign.dockbarx-launcher
- src: gantsign.gitkraken
- src: gantsign.intellij
- src: gantsign.keyboard
- src: gantsign.lightdm
- src: gantsign.maven-color
- src: gantsign.maven-notifier
- src: https://github.com/gantsign/ansible-role-unison
  name: gantsign.unison
- src: gantsign.visual-studio-code
- src: https://github.com/gantsign/ansible-role-xdesktop
  name: gantsign.xdesktop
- src: gantsign.zram-config
