# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale: en-US
title: Minimal Mistakes
title_separator: '-'
name: &name 'Michael Rose'
description: &description 'A flexible Jekyll theme for your blog or site with a minimalist aesthetic.'
url: https://mmistakes.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: /minimal-mistakes # the subpath of your site, e.g. "/blog"
repository: mmistakes/minimal-mistakes
teaser: # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
# breadcrumbs: no # true, false (default)
words_per_minute: 200
atom_feed:
  path: # blank (default) uses feed.xml

# Social Sharing
twitter:
  username: &twitter 'mmistakes'
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - 'https://twitter.com/mmistakes'
    - 'https://facebook.com/michaelrose'

# Site Author
author:
  name: *name
  avatar: michael-rose.jpg
  bio: 'Just another boring, tattooed, time traveling, designer.'
  location: 'Buffalo, NY'
  email:
  uri: https://mademistakes.com
  github: mmistakes
  twitter: *twitter


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'


# Conversion
markdown: kramdown
highlighter: rouge
lsi: no
excerpt_separator: "\n\n"
incremental: no


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: no
  auto_ids: yes
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: no


# Collections
collections:
  docs:
    output: yes
    permalink: /:collection/:path/
  recipes:
    output: yes
    permalink: /:collection/:path/
  pets:
    output: yes
    permalink: /:collection/:path/
  portfolio:
    output: yes
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: yes
      read_time: yes
      comments: yes
      share: yes
      related: yes
  # _pages
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      author_profile: yes
  # _docs
  - scope:
      path: ''
      type: docs
    values:
      layout: single
      read_time: no
      author_profile: no
      share: no
      comments: no
      sidebar:
        nav: docs


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Include minimal-mistakes from Gemfile 
theme: minimal-mistakes
