source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!

gem 'github-pages', '227', group: :jekyll_plugins

# Required for Jekyl serve on Ruby 3
gem 'webrick', '1.7', group: :jekyll_plugins

# If you want to use Jekyll native, uncomment the line below.
# To upgrade, run `bundle update`.

# gem "jekyll"

# Install minimal-mistakes theme
gem 'minimal-mistakes-jekyll', '4.24.0'

# If you have any plugins, put them here!
group :jekyll_plugins do
  # gem "jekyll-archives"
  gem 'html-proofer', '4.4.1'
end
